name: Build FFmpeg Fully with All Codecs

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        include:
          - os: ubuntu-24.04
            artifact_name: ffmpeg-ubuntu-full
          - os: windows-2022  
            artifact_name: ffmpeg-windows-full

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 专门为Windows设置MSYS2环境
    - name: Setup MSYS2 (Windows only)
      if: matrix.os == 'windows-2022'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          pkg-config
          diffutils
          nasm
          yasm
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-libass
          mingw-w64-x86_64-fdk-aac
          mingw-w64-x86_64-fontconfig
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-lame
          mingw-w64-x86_64-libogg
          mingw-w64-x86_64-libopus
          mingw-w64-x86_64-libtheora
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-libvpx
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-x264
          mingw-w64-x86_64-x265
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-zimg
          mingw-w64-x86_64-sdl2
          mingw-w64-x86_64-openal
          mingw-w64-x86_64-rubberband
          mingw-w64-x86_64-twolame
          mingw-w64-x86_64-speex
          mingw-w64-x86_64-wavpack
          mingw-w64-x86_64-kvazaar
          mingw-w64-x86_64-rav1e
          mingw-w64-x86_64-libaom
          mingw-w64-x86_64-dav1d
          mingw-w64-x86_64-svt-av1

    - name: Checkout FFmpeg source
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-src
        cd ffmpeg-src
      shell: bash

    - name: Setup build environment
      run: |
        chmod +x $GITHUB_WORKSPACE/scripts/setup-build.sh
        $GITHUB_WORKSPACE/scripts/setup-build.sh
      shell: bash

    - name: Build FFmpeg
      shell: ${{ matrix.os == 'windows-2022' && 'msys2 {0}' || 'bash' }}
      run: |
        chmod +x $GITHUB_WORKSPACE/scripts/build-ffmpeg.sh
        $GITHUB_WORKSPACE/scripts/build-ffmpeg.sh
      env:
        OS_TYPE: ${{ matrix.os }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ${{ github.workspace }}/ffmpeg-build/
        retention-days: 7

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/ffmpeg-build/*